---
api_key: RPq124TkDHwsYSY2FnOni9HJqfyMKULEmXr10hL1tVAN3RcREr

reporters:
  - name: random
    type: Random

  - name: haproxy_log_requests
    type: HaproxyLogRequests
    logfile: /var/log/haproxy.log

widgets:
  - type: Box
    id: 506475
    reporter: random
    value: value
