---
api_key: YOUR_API_KEY

reporters:
  - name: random
    type: Random

  - name: haproxy_log_requests
    type: HaproxyLogRequests
    options:
      log_file: haproxy.log

widgets:
  - type: Box
    id: 506475
    reporter: random
    value:
      current: :value
